### ISSUE TITLE
Declare libgraphicsmagick1-dev dependency

### ISSUE THREAD

**Issue by miguelpeixe** [mapascoletivos/api-service#43]
[imager package requires libgraphicsmagick1-dev](https://github.com/imagerjs/imager#dependencies)
Just spent 1 hour figuring out why wasn't installing. Turns out: no libgraphicsmagick1-dev.

Other dependencies are also missing on README.md (off the top my mind: mongodb, node, npm, etc)

**Comment by vgeorge** [comment]
Closed due to inactivity.
